# docker-compose 파일 버전
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
    depends_on:
      - triton
      - database

  triton:
    build: ./triton
    shm_size: '1g'
    ports:
      - "8000:8000"  # HTTP 포트
      - "8001:8001"  # gRPC 포트
      - "8002:8002"  # Metrics 포트
    deploy:          # GPU 사용을 위한 설정
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  database:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
